#!/bin/bash
eSkill()
{
kill -15 $1 || kill -2 $1 || kill -1 $1 || kill -9 $pid
}

re='^([[:digit:]]{4}|[[:digit:]]{5})$'

if [[ $1 =~ $re ]]; then
  echo "running"
  eSkill $1
  exit
fi

cPage=$(ps aux)
gResult=$(echo "$cPage" | grep -ni $1 | sed '/pseKill/d' | sed '/^.\{150\}./d' )
echo $gResult
aLines=$(echo "$gResult" | wc -l)

if [ $aLines -gt "1" ]; then
  echo "$rLineNo"
  echo -e "\e[1m\e[31mMultiple Results found:\e[0m"
  echo "$gResult" | sed 's/.\{4\}\(.\{15\}\).\{63\}/\n\1/'
  echo -e "\e[1m\e[32m\nPlease rerun command with specific name/location or PID\e[0m\n"
elif [[ $gResult = "" ]]; then
  echo "Nothing found"
else
  echo "calling"
  pid=$(echo "$gResult" | sed 's/[^[:space:]][^[:space:]]*[[:space:]][[:space:]]*\([0-9]\{1,5\}\).*/\1/')
  echo "$pid"
  eSkill $pid
fi



  # rLineNo=$(echo "$gResult" | sed 's/:.*//')
